# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NiWu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NiWu
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'MMPopupView'
pod 'MJRefresh'
pod 'YYWebImage'
pod 'MJExtension'
pod 'UMengAnalytics-NO-IDFA'
pod 'SDCycleScrollView'
pod 'PYSearch'
pod 'AMPopTip'
pod 'ZFPlayer'
pod ‘Masonry’

end
